[build]
  command = "cd admin-dashboard && npm install && npm run build"
  publish = "admin-dashboard/dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_version = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"