[build]
  command = "cd admin-dashboard && npm run build"
  publish = "admin-dashboard/dist"
  base = "/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["admin-dashboard/dist/**"]

[dev]
  command = "cd admin-dashboard && npm run dev"
  port = 3000
  targetPort = 3000