[build]
  command = "cd admin-dashboard && npm run build"
  publish = "admin-dashboard/dist"
  base = "/"

[functions]
  node_version = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200